### ISSUE TITLE
github.com/malisit/kolpa/data/en_US/user: no such file or directory

### ISSUE THREAD

**Issue by JeffreyBool** [malisit/kolpa#20]
github.com/malisit/kolpa/data/en_US/user: no such file or directory

**Comment by malisit** [comment]
Hi, thanks for pointing this issue out. GOPATH related issues should be solved with last few commits. Please close the issue if your problem no longer exists with latest version.

**Comment by JeffreyBool** [comment]
I'm just using the latest package, and I'm in `en_US ` directory does not see the `user` file

**Comment by malisit** [comment]
Are you trying to generate use agent?

**Comment by JeffreyBool** [comment]
Yes

**Comment by malisit** [comment]
Okay, here's the thing; the generic generator works in a way that when it can't find a file named `x_y`, it then looks for a file named `x`. So when you want to generate user agent it first tries to get the `user_agent` file and when it can't find it, it then proceeds to look for `user`. You don't see the first error because it's handled differently. The problem here is that it actually needs to find the `user_agent` file and it shouldn't go for `user` file. 

What I mean is, you don't need a `user` file. You only need `user_agent` file in order to generate a user agent. Previous versions of this package would use GOPATH env variable but IIRC with Go 1.8+ the actual go path (not the env var one) would set to ~/go if the GOPATH env var is not set particularly. So, that's why it wasn't able to find the data files if the GOPATH wasn't set in the version right before my last three commits. With Go 1.8+ we can get the actual go path within go code without using `os` because it doesn't need to be the value of the env var. That's what I fixed and the sample code in `README.md` works like a charm for me right now. You should just do `go get github.com/malisit/kolpa` again.

**Comment by JeffreyBool** [comment]
ok, thanks~

**Comment by zgldh** [comment]
> ok, thanks~

Please try with my pull request #21
